# -*- coding: utf-8 -*-
"""AlgorithmsFinalProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p55vCHIzs8NtrnHijhWCPw4gfMw5cGCi
"""

tutors_BAM = [("Tutor 1","Roberta", "3rd Year BAM Student", "GPA: 99"), ("Tutor 2", "Lorenza", "2nd Year BAM Student", "GPA: 92"), ("Tutor 3","Emilia", "2nd Year BAM Student", "GPA: 88")]
tutors_BAS = [("Tutor 1", "Jose", "4th Year Architecture Student", "GPA: 91"), ("Tutor 2","Constanza", "2nd Year Architecture Student", "GPA: 94"), ("Tutor 3","Laura", "2nd Year Architecture Student", "GPA: 89")]
tutors_BBSS = [("Tutor 1","Pablo", "3rd Year BBSS Student", "GPA: 93"), ("Tutor 2","Valeria", "4th Year BBSS Student", "GPA: 97"), ("Tutor 3","Daniela", "3rd Year BBSS Student", "GPA: 89")]
tutors_BBA = [("Tutor 1","Valentina", "3rd Year BBA Student", "GPA: 92"), ("Tutor 2","Lucas", "4th Year BBA Student", "GPA: 99"), ("Tutor 3","Fernando", "3rd Year BBA Student", "GPA: 91")]
tutors_BCDM = [("Tutor 1","Lucia", "3rd Year Communications Student", "GPA: 92"), ("Tutor 2","Ana", "4th Year Communications Student", "GPA: 100"), ("Tutor 3","Sofia", "3rd Year Communications Student", "GPA: 90")]
tutors_BCSAI= [("Tutor 1","Gilberto", "2nd Year BCSAI Student", "GPA: 94"), ("Tutor 2","Carlota", "2nd Year BCSAI Student", "GPA: 91"), ("Tutor 3","Tomas", "2nd Year BCSAI Student", "GPA: 98")]
tutors_BDBA = [("Tutor 1","Noah", "2nd Year BBA and Data Student", "GPA: 95"), ("Tutor 2","Elard", "2nd Year BBA and Data Student", "GPA: 95"), ("Tutor 3","Jimena", "4th Year Data Student", "GPA: 92")]
tutors_BiD = [("Tutor 1","Daph", "2nd Year Design Student", "GPA: 94"), ("Tutor 2","Sophie", "2nd Year Design Student", "GPA: 91"), ("Tutor 3","Patricio", "3rd Year Design Student", "GPA: 88")]
tutors_BiE = [("Tutor 1","Daniel", "2nd Year Economics Student", "GPA: 93"), ("Tutor 2","Pedro", "3rd Year Economics Student", "GPA: 89"), ("Tutor 3","Oscar", "2nd Year Economics Student", "GPA: 97")]
tutors_BIR = [("Tutor 1","Cata", "2nd Year IR Student", "GPA: 99"), ("Tutor 2","Cande", "2nd Year BBA and IR Student", "GPA: 91"), ("Tutor 3","Mauricio", "4th Year IR Student", "GPA: 90")]
tutors_PPLE = [("Tutor 1","Isabel", "2nd Year PPLE Student", "GPA: 87"), ("Tutor 2","Natalia", "2nd Year PPLE and Data Student", "GPA: 96"), ("Tutor 3","Laura", "4th Year PPLE Student", "GPA: 93")]
tutors_LAW = [("Tutor 1","Camila", "3rd Year Law Student", "GPA: 97"), ("Tutor 2","Bernando", "2nd Year BBA and Law Student", "GPA: 87"), ("Tutor 3","Ana Paula", "2nd Year Law Student", "GPA: 90")]

list_bachelors = ["Bachelor in Applied Mathematics","Bachelor in Architectural Studies", "Bachelor in Behavior and Social Sciences", "Bachelor in Business Administration",
                  "Bachelor in Communiation and Digital Media", "Bachelor in Computer Science and Artificial Intelligence", "Bachelor in Data and Business Analytics", 
                  "Bachelor in Deisgn", "Bachelor in Economics", "Bachelor in International Relations", "Bachelor in Philosophy, Politics, Economics and Law", 
                  "Bachelor in Law"]

first_year = dict()

first_year = {"Bachelor in Applied Mathematics": ["Mathematical Fundamentals","Fundamentals of Algebra",
                                                  "Differential Calculus", "Probability and Statistics", "Research Methods and Design",
                                                  "Applied Maths: Energy and Sustainability", "Linear Algebra", "Discrete Mathematics",
                                                  "Integral Calculus", "Programming for Applied Mathematics", "Applied Math: Finance & Banking"],
              "Bachelor in Architectural Studies": ["Design Studio 1", "Graphic Communication 1", "Applied Mathematics in Architecture 1",
                                                    "Architecture Histories and Contexts", "Interpersonal Skills", "Design Studio 2","Graphic Communication 2",
                                                    "Architectural Geometry 1", "Applied Physics in Architecture 1", "Business Management", 
                                                    "Digital Tools and Operations"],
              "Bachelor in Behavior and Social Sciences": ["Learning to Observe, Experiment and Survey","Fundamentals of Social Science",
                                                           "Writing Skills","Data Insights and Visualizations", "Introduction to Business Managmente", 
                                                           "Fundamentals of Statistics and Probability", "Technology Trends Today", "Fundamentals of Data Analysis", 
                                                           "Simulating and Modeling to Understand Change", "The Big History of Ideas and Innovation", 
                                                           "Presentation Skills", "Fundamentals of Human Behavior"],
              "Bachelor in Business Administration": ["Financial Accounting", "Managment Tools and Principles", "Applied Business Mathematics", 
                                                      "Marketing Fundamentals", "Building Powerful Relationships", "Research & Academic Writing Skills", 
                                                      "Cost Accounting", "Mathematics for Management", "Introduction to Programming", "Corporate Finance",
                                                      "Microeconomics"],
              "Bachelor in Communiation and Digital Media": ["Communication Foundations", "Photography", "Globalization and Cross-Cultural Communication",
                                                             "Writing for Media", "Oral Skills", "Writing Skills", "Public Opinion, Persuasion and Engagement", 
                                                             "Visual and Digital Media Culture", "Graphic Design and Infographics", "Public Affairs and Non-Market Strategies",
                                                             "Technology Fluency", "Introduction to Management"],
              "Bachelor in Computer Science and Artificial Intelligence":["Fundamentals of Human Behavior","Fundamentals of Social Science", "Fundamentals of Technology & Innovation",
                                                                          "Introduction to Management", "Fundamentals of Probability Statistics", "Learning to Observe, Experiment & Survey", 
                                                                          "Simulating and Modeling to Understand Change", "The Big History of Ideas & Innovation", "Principles of Programming"],
              "Bachelor in Data and Business Analytics":["Learning to Observe, Experiment and Survey", "Fundamentals of Social Science", "Writing Skills",
                                                         "Data Insights & Visualizations", "Introduction to Business Management", "Fundamnetals of Statistics and Probability",
                                                         "Technology Trends Today", "Fundamentals of Data Analysis", "Simulating and Modeling to Understand Change", "The Big History of Ideas & Innovation",
                                                         "Presentation Skills", "Fundamentals of Human Behavior"],
              "Bachelor in Deisgn": ["Intro to Design Studio 1", "Design History 1", "Design Skills 1", "Psychology and User Center Design", "Presentation Skills",
                                     "Writing Skills", "Intro to Design Studio 2", "Design History 2", "Visualization and Representation Techniques", "Sociology and Culture"],
              "Bachelor in Economics": ["Mathematics for Economists", "Foundation of Microeconomics", "Foundations of Macroeconomics", "Economic History",
                                        "Impact Writing Lab", "Programming for Economists", "Development and Growth Economics", "International Trade and Monetary System", 
                                        "Probability and Statistics", "Game Theory", "Research Methods for Economists","Programming for Economists 2"],
              "Bachelor in International Relations": ["History of International Relations up to 1945", "Introduction to Political Science", "Microeconomics", 
                                                      "Political Theory", "Languages 1", "Unplugged 1: Introduction to Agenda 2030", "Contemporary Global History", 
                                                      "Macroeconomics", "Languages 2", "Unplugged 2: Systems Thinking", "International Relations Theory"],
              "Bachelor in Philosophy, Politics, Economics and Law": ["Mathematics", "Elementary Logic", "European Legal History", "Introduction to Political Science", "Writing Skills", 
                                                                      "Research Methods and Data Analysis", "Microeconomics", "Social Seminar 1", "History of Ancient and Medieval Philosophy", 
                                                                      "Constitutional Law", "Government and Comparative Politics"],
              "Bachelor in Law": ["European Legal History", "Constitutional Law", "Introduction to Private Law: Civil Law", "Economics", "Unplugged 1", 
                                  "Accounting and Finance", "Criminal Law 1", "Civil Law Contracts", "Unplugged 2", "Legal Thought", "Administrative Law 1"]}                                               

for key, value in first_year.items() :
    print(key, value)

def class_search(bachelor):
    for key, value in first_year.items():
        if key==bachelor:
            print(value)

def contact_tutor():
  print()
  print("It is time to contact your tutor!")
  print("This information will be sent directly to your choosen tutor:")
  print("All this information is confidential between you and your tutor.")
  print()
  your_name = input("What is your full name (include last name)?")
  your_bachelor = input("What is your bachelor?")
  your_year = input("What year are you in?")
  email = input("Enter your email:")
  phone = input("What is your phone number?")
  help = input("Briefly describe in what ways you need help with:")
  student_info = [your_name, your_bachelor, your_year, email, phone, help]
  print()
  print("Summary of Information:",student_info)
  print()
  print("Your information has been correctly sent to your tutor!")  
  print("Now, you have to wait until you receive a message from them.")

def tutorIE():
    print("Choose the bachelor you are taking (If you are doing a dual degree choose the bachelor linked to the subject you need help with).")
    print("Your options are as follows: \n 1. Bachelor in Applied Mathematics \n 2. Bachelor in Architectural Studies"
    "\n 3. Bachelor in Behavior and Social Sciences \n 4. Bachelor in Business Administration, \n 5. Bachelor in Communication and Digital Media"
    "\n 6. Bachelor in Computer Science and Artificial Intelligence \n 7. Bachelor in Data and Business Analytics"
    "\n 8. Bachelor in Design \n 9. Bachelor in Economics \n 10. Bachelor in International Relations"
    "\n 11. Bachelor in Philosophy, Politics, Economics and Law \n 12. Bachelor in Law")
    bachelor = eval(input("What number corresponds to the bachelor you need help with?"))
    
    while bachelor != "":
      if bachelor == 1:
        print()
        print("The bachelor you have selected is:", list_bachelors[0])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[0])
        break
      elif bachelor == 2:
        print()
        print("The bachelor you have selected is:", list_bachelors[1])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[1])
        break
      elif bachelor == 3:
        print()
        print("The bachelor you have selected is:", list_bachelors[2])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[2])
        break
      elif bachelor == 4:
        print()
        print("The bachelor you have selected is:", list_bachelors[3])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[3])
        break
      elif bachelor == 5:
        print()
        print("The bachelor you have selected is:", list_bachelors[4])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[4])
        break
      elif bachelor == 6:
        print()
        print("The bachelor you have selected is:", list_bachelors[5])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[5])
        break
      elif bachelor == 7:
        print()
        print("The bachelor you have selected is:", list_bachelors[6])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[6])
        break
      elif bachelor == 8:
        print()
        print("The bachelor you have selected is:", list_bachelors[7])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[7])
        break
      elif bachelor == 9:
        print()
        print("The bachelor you have selected is:", list_bachelors[8])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[8])
        break
      elif bachelor == 10:
        print()
        print("The bachelor you have selected is:", list_bachelors[9])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[9])
        break
      elif bachelor == 11:
        print()
        print("The bachelor you have selected is:", list_bachelors[10])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[10])
        break
      elif bachelor == 12:
        print()
        print("The bachelor you have selected is:", list_bachelors[11])
        print()
        print("Your bachelor has the following class options:")
        class_search(list_bachelors[11])
        break
      else:
        print("The bachelor you have selected is not valid. Try again.")
        
        
        print("Your options are as follows: \n 1. Bachelor in Applied Mathematics \n 2. Bachelor in Architectural Studies"
        "\n 3. Bachelor in Behavior and Social Sciences \n 4. Bachelor in Business Administration, \n 5. Bachelor in Communication and Digital Media"
        "\n 6. Bachelor in Computer Science and Artificial Intelligence \n 7. Bachelor in Data and Business Analytics"
        "\n 8. Bachelor in Design \n 9. Bachelor in Economics \n 10. Bachelor in International Relations"
        "\n 11. Bachelor in Phçilosophy, Politics, Economics and Law \n 12. Bachelor in Law")
        bachelor = eval(input("What number corresponds to the bachelor you need help with?"))

    print()
    course = input("What class from the list above do you want to tutoring from:")

    if bachelor == 1:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BAM)
    elif bachelor == 2:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BAS)
    elif bachelor == 3:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BBSS)
    elif bachelor == 4:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BBA)
    elif bachelor == 5:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BCDM)
    elif bachelor == 6:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BCSAI)
    elif bachelor == 7:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BDBA)
    elif bachelor == 8:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BiD)
    elif bachelor == 9:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BiE)
    elif bachelor == 10:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_BIR)
    elif bachelor == 11:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_PPLE)
    elif bachelor == 12:
      print()
      print("These are the available tutors for your class and degree:")
      print(tutors_LAW)
  
    print()
    tutor_n= eval(input("What is the number of the tutor you are interested in? (only include the number)"))
    
    if bachelor == 1:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BAM[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BAM[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BAM[2])
    elif bachelor == 2:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BAS[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BAS[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BAS[2])
    elif bachelor == 3:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BBA[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BBA[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BBA[2])
    elif bachelor == 4:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BBSS[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BBSS[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BBSS[2])
    elif bachelor == 5:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BCDM[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BCDM[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BCDM[2])
    elif bachelor == 6:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BCSAI[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BCSAI[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BCSAI[2])
    elif bachelor == 7:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BDBA[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BDBA[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BDBA[2])
    elif bachelor == 8:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BiD[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BiD[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BiD[2])
    elif bachelor == 9:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_BiE[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BiE[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BiE[2])
    elif bachelor == 10:
        if tutor_n == 1:
          print("Your choosen tutor is:", tutors_BIR[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_BIR[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_BIR[2])
    elif bachelor == 11:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_PPLE[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_PPLE[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_PPLE[2])
    elif bachelor == 12:
        if tutor_n == 1:
          print("Your choosen tutor is:" , tutors_LAW[0])
        elif tutor_n == 2:
          print("Your choosen tutor is:", tutors_LAW[1])
        elif tutor_n == 3:
          print("Your choosen tutor is:", tutors_LAW[2])

      
    contact_tutor()

tutorIE()